/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Input: typeof import('./components/ui/input/Input.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    LayoutHeader: typeof import('./components/layout/LayoutHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/ui/table/Table.vue')['default']
    TableBody: typeof import('./components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./components/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./components/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./components/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./components/ui/table/TableRow.vue')['default']
  }
}
